# Site Name
site_name: NEW-SITE
site_description: "Coming Soon" 

# Navigation menu
nav:
  - Overview: new-site.md

# Existing files but not in nav
not_in_nav: |
  ksb.md
  quiz/*
  images/README.md
  0-discovery/*.md
  1-introduction/*.md
  a-agile/*.md
  b-devops/*.md
  c-git/*.md
  d-cloud/*.md
  e-databases/*.md
  f-python/*.md
  presentations/*.md
  index.md
  setup.md

# Theme
theme:
    feaures:
      - tabs
    name: material
    icon:
      logo: material/cloud
    static_templates:
      - 404.html

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: false
  - pymdownx.tilde
