# Site name
site_name: DE5-M4 ~ Planning a Data Engineering Project 

# Navigation menu
nav:
  - Overview: index.md
  - "A: Agile":
    - "Agile and DevOps": a-agile/index.md
    - "Exercise 1: Design Steps"   : a-agile/ex1-design-steps.md
    - "Exercise 2: Application"    : a-agile/ex2-application.md
    - "Exercise 3: Work Project": a-agile/ex3-work-project.md
  - "B: Product Planning":
    - "Agile Product Planning": b-plan/index.md
    - "Exercise 1: Identify Epics" : b-plan/ex1-identify-epics.md
    - "Exercise 2: User Stories"   : b-plan/ex2-user-stories.md
    - "Exercise 3: Estimate Effort": b-plan/ex3-estimate-effort.md
    - "Exercise 4: Sprint Planning": b-plan/ex4-sprint-planning.md
  - "C: Git and GitHub": c-git/index.md
  - "D: Cloud": d-cloud/index.md
  - "E: Storage": e-storage/index.md
  - "F: Python for Data": f-python/index.md
  - Presentations: presentations/index.md
  - File Downloads: downloads.md

# Existing files but not in nav
not_in_nav: |
  ksb.md
  quiz/*
  images/README.md
  c-git/e*
  d-cloud/e*
  e-storage/e*
  f-python/e*

# Theme
theme:
    feaures:
      - tabs
    name: material
    icon:
      logo: material/database
    static_templates:
      - 404.html

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: false
  - pymdownx.tilde

plugins:
  - search
