# Site name
site_name: Module 4 - Planning Data Engineering Product
dev_addr: '0.0.0.0:8000'

# Navigation menu
nav:
  - Overview: index.md

  - Agenda:
    - Day 1: agenda/day1.md
    - Day 2: agenda/day2.md
    - Day 3: agenda/day3.md
    - Day 4: agenda/day4.md

  - "Day 1 - Agile Foundations":
    - "How are products designed?": day1/agile/how-instructions.md
    - "Apply design process to a scenario": day1/agile/scenario.md
    - "Identify Epics": day1/planning/epics.md
    - "Write User Stories in groups": day1/planning/user-stories.md
    - "Plan a 2-week sprint": day1/planning/sprint-planning.md

  - "Day 2 - Technical Foundation":
    - "Lab 1 ~ Working locally with Git": day2/source-control/git-locally.md
    - "Lab 2 ~ Create a Repo in GitHub": day2/source-control/github-repo.md
    - "Lab 3 ~ Create an Issue": day2/source-control/github-create-issue.md
    - "Lab 4 ~ Fork a Repository": day2/source-control/github-forking.md
    - "Lab 5 ~ Create a Pull Request": day2/source-control/github-pull-request.md
    - "Cloud ~ Core Building Blocks": day2/cloud/building-blocks.md
    - "Cloud Architecture Scenarios": day2/cloud/architecture.md
    - "Cloud Architecture": day2/cloud/scenario.md

  - "Day 3 - Database Design & Python":
    - "Workplace Storage & Databases": day3/storage/examples.md
    - "Lab 1 ~ Create Amazon S3 Bucket": labs/amazon-s3-bucket.md
    - "Lab 2 ~ Core Azure Storage Products": labs/azure-storage-products.md
    - "Lab 3 ~ Google Cloud Storage": labs/google-cloud-storage.md
    - "Lab 4 ~ AWS Acquiring & Storing Data": labs/aws-acquiring-storing-data.md
    - "1. Requirements Analysis": day3/storage/analysis.md
    - "2. Create Conceptual Data Model": day3/storage/conceptual.md
    - "3. Logical Model & Design Decisions": day3/storage/logical.md
    - "Docker container": day3/docker.md
    - "Python TDD": day3/python/tdd.md

  - "Day 4 - Integration Project":
    - "Introduce Day 4 activity": day4/product-planning.md

  - Resources: resources.md

not_in_nav: |
  404.md
  trainer.md
  day1/build-a-wall.md
  day1/agile/how-solution.md
  day1/planning/epics-solution.md
  day1/planning/possible-user-stories.md
  day1/planning/planning-poker.md
  day1/planning/sprint-solution.md


# Theme
theme:
    features:
      - toc.integrate
      - content.code.copy
    name: material
    icon:
      logo: material/database

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - meta
  - tables
  - toc:
      permalink: false
      toc_depth: 2

  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: false
  - pymdownx.tilde

plugins:
  - search
  - glightbox


