[project]
site_name = "Module 4 - Planning Data Engineering Product"
dev_addr = "0.0.0.0:8000"

nav = [
  {"Overview" = "index.md"},
  {"Agenda" = [
    {"Day 1" = "agenda/day1.md"},
    {"Day 2" = "agenda/day2.md"},
    {"Day 3" = "agenda/day3.md"},
    {"Day 4" = "agenda/day4.md"},
  ]},
  {"Day 1 ~ Agile Foundations" = [
    {"How are products designed?" = "day1/agile/how-design-steps.md"},
    {"Apply design process to a scenario" = "day1/agile/scenario.md"},
    {"Agile artefacts" = "day1/agile/artefacts.md"},
    {"Identify Epics" = "day1/planning/epics.md"},
    {"Write User Stories in groups" = "day1/planning/user-stories.md"},
    {"Planning Poker Setup" = "day1/planning/estimate-effort.md"},
    {"Plan a 2-week sprint" = "day1/planning/sprint-planning.md"},
  ]},
  {"Day 2 ~ Technical Foundation" = [
    {"Lab 1: Working locally with Git" = "day2/source-control/git-locally.md"},
    {"Lab 2: Create a Repo in GitHub" = "day2/source-control/github-repo.md"},
    {"Lab 3: Create an Issue" = "day2/source-control/github-create-issue.md"},
    {"Lab 4: Fork a Repository" = "day2/source-control/github-forking.md"},
    {"Lab 5: Create a Pull Request" = "day2/source-control/github-pull-request.md"},
    {"Cloud ~ Core Building Blocks" = "day2/cloud/building-blocks.md"},
    {"Cloud Architecture Scenarios" = "day2/cloud/architecture.md"},
    {"Cloud Architecture" = "day2/cloud/scenario.md"},
  ]},
  {"Day 3 ~ Database Design & Python" = [
    {"1. Clone Repo to the VM" = "day3/python/setup.md"},
    {"2. Explore the Project Structure" = "day3/python/scaffold-tour.md"},
    {"3. The Supporting Files" = "day3/python/scaffold-files.md"},
    {"4. Run the Tests Locally" = "day3/python/local-test.md"},
    {"5. Lint Python Code" = "day3/python/coverage-ruff.md"},
    {"6. GitHub Actions" = "day3/python/ci-bridge.md"},
    {"7. Python CI Pipeline" = "day3/python/python-ci.md"},
    {"Docker Container" = "day3/docker.md"},
    {"1. Requirements Analysis" = "day3/storage/1-analysis.md"},
    {"2. Create Conceptual Data Model" = "day3/storage/2-conceptual.md"},
    {"3. Logical Model & Design Decisions" = "day3/storage/3-logical.md"},
    {"Lab 1 ~ Create Amazon S3 Bucket" = "labs/amazon-s3-bucket.md"},
    {"Lab 2 ~ Core Azure Storage Products" = "labs/azure-storage-products.md"},
    {"Lab 3 ~ Google Cloud Storage" = "labs/google-cloud-storage.md"},
  ]},
  {"Day 4 ~ Costing & Presentations" = [
    {"Cloud Pricing Calculators" = "day4/costing/calculators.md"},
    {"More Complex Calculations" = "day4/costing/scenarios.md"},
    {"Presentation Prep" = "day4/presentation.md"},
  ]},
  {"Resources" = "resources.md"},
]


[project.theme]
variant = "classic"

features = [
  "announce.dismiss",
  "content.code.annotate",
  "content.code.copy",
  "content.code.select",
  "toc.integrate",

  #"content.action.edit",
  #"content.action.view",
  #"header.autohide",
  #"navigation.expand",
  #"navigation.footer",
  #"navigation.instant",
  #"navigation.instant.prefetch",
  #"navigation.instant.progress",
  #"navigation.path",
  #"navigation.sections",
  #"navigation.tabs",
  #"navigation.tabs.sticky",
  #"navigation.top",
  #"navigation.tracking",
  #"search.highlight",
  #"toc.follow",
]
    
[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"
    
[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"
    
[project.theme.icon]
logo = "material/database"
    
